@url = http://localhost:5000

###
GET {{url}}/orders-service

###
GET {{url}}/orders-service/orders

###
GET {{url}}/orders-service/orders/1

###
POST {{url}}/orders-service/orders
Content-Type: application/json

###
POST {{url}}/orders/send
Content-Type: application/json

{
  "orderId": 1,
  "notes": "Order notes"
}

###
GET {{url}}/products-service

###
GET {{url}}/products-service/products

###
GET {{url}}/products-service/products/1

###
GET {{url}}/users-service

###
GET {{url}}/users-service/users

###
GET {{url}}/users-service/users/1